### ISSUE TITLE
Configure `eslint` for great TypeScript linting

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource-management-portal#148]
Configure with `--fix` to improve the formatting experience.

**Comment by deril1** [comment]
https://github.com/microsoft/opensource-portal/issues/148#issue-652767100

**Comment by Shegox** [comment]
Hi there, 
did you already started anything in this direction. If not I would be happy to set it up and cleaning up a bit of the existing code base using the eslint rules. 
If I do that, I would have a few points, where I would please like your input on how to best set it up:
- What would be our target configuration? I would go for `eslint:recommended` and `plugin:@typescript-eslint/recommended`, which are the recommended rules by the [typescript-eslint project](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs).
- A first run shows that there are quite a few errors (9k+) and so I would start with an empty rule set and add one rule after another and fixing the issues along the way. I saw that only a handful of them would be auto fixable (like 500)
    ```
    ✖ 9978 problems (8217 errors, 1761 warnings)
    491 errors and 0 warnings potentially fixable with the `--fix` option.
    ```
- With having a linter setup, it probably makes sense to setup a CI-check. Would adding it as a GitHub Action would be a good fit?

**Comment by jeffwilcox** [comment]
Hey @Shegox 👋

I do want to get to a good place to do this, but at least on my side, I'm trying to do some heroic refactoring of our Microsoft-side of this app... and so there's still some churn in the hopper.

My goal is to be able to move to entirely using this open project to help everyone, and I think we're really close.

I'm personally looking to get some unit tests in place, finally, moving to use `jest` over `mocha`, etc.; and so my personal prioritization as I have time here is:

1. refactor cleanup to be able to use this open project exclusively
2. some early unit testing
3. code cleanup in time

Now, I do think some _targeted_ improvements to specific files could make sense, but until I get some more changes in, I worry we'll be in for some tough merge conflicts.

I'll also update the title, since you're right, `typescript-eslint` is no longer recommended over just core eslint and the right plug-ins.

**Comment by nschonni** [comment]
I opened up https://github.com/microsoft/opensource-portal/pull/199 just as a "line in the sand" without impacting the refactoring

**Comment by jeffwilcox** [comment]
Major kudos to @nschonni on landing all this work!
