### ISSUE TITLE
Feature: Change how GitHub ID for repo is displayed

### ISSUE THREAD

**Issue by diberry** [microsoft/opensource-management-portal#971]
**Is your feature request related to a problem? Please describe.**
Sorta - when linked to GitHub to create a Codespace for an Azure-samples repo, it isn't obvious where to go to get the required **repo ID** needed in the link: `https://github.com/codespaces/new?azure-portal=true&hide_repo_select=true&ref=main&repo=721389005`

**Describe the solution you'd like**
The id is under the visually stylized table for the repo. Can we move it into the highlights (?) table and give its value, and also provide the URL code and button to create the Codespace? It would make it more obvious how to use the value and give people the correct code to use it in comms. Sort of how some of the samples have "Deploy to Azure" buttons. 

Highlights table: 
![image](https://github.com/microsoft/opensource-management-portal/assets/41597107/aad10fcb-27b4-41d6-a826-d37e065ed7f9)

Bottom of page where ID is:
![image](https://github.com/microsoft/opensource-management-portal/assets/41597107/d148a57d-4a0e-4aea-9bc9-fdd24753519e)

**Comment by jeffwilcox** [comment]
Sure, happy to do this. Also interesting to know that someone other than me is using the native GitHub repo ID regularly...

**Comment by seesharprun** [comment]
GitHub Codespaces almost requires it for deep linking.

**Comment by jeffwilcox** [comment]
It's probably worth someday considering an easy "create codespace" button; however, can't the user also just go to the top right's "open on github.com" link, and use the native GitHub experience to create a Codespace? I feel like we try and not duplicate too many native experiences on our own for example.

Anyway, this is now in production internally, hope this helps.

![Image](https://github.com/microsoft/opensource-management-portal/assets/427913/f282c8c7-ae49-4a7e-8f5d-ba3d46abfc49)
