### ISSUE TITLE
Octicons name changes in latest version of primer/octicons

### ISSUE THREAD

**Issue by DevOptimusPrime** [microsoft/opensource-management-portal#999]
**Describe the bug**
The octicons `primitive-dot` and `text-size` have been changed to `dot-fill` and `typography` respectively in `@primer/octicons:19.8.0` 

**Deployment environment**
Azure webapp

**To Reproduce**
Deploy the current version
Navigate to the `Repos` page for a given Org
Observe you get a stack trace looking for the older and now missing icon name

**Expected behavior**
Page should load

**Comment by jeffwilcox** [comment]
Thanks for the report...

Internally we haven't used the server-rendered/pug site for so long that we missed this and have no tests on that.

Hoping to be able to open source the Vite/React site we use instead...

**Comment by DevOptimusPrime** [comment]
That would be awesome - we'd love to move to that eventually 🚀
